-- Table: [TA].[price_feature_daily]

CREATE TABLE [TA].[price_feature_daily] (
    [symbol] [varchar](32) NOT NULL,
    [trade_date] [date] NOT NULL,
    [sma_10] [decimal](18,6) NULL,
    [sma_20] [decimal](18,6) NULL,
    [sma_50] [decimal](18,6) NULL,
    [sma_150] [decimal](18,6) NULL,
    [sma_200] [decimal](18,6) NULL,
    [ema_21] [decimal](18,6) NULL,
    [ema_50] [decimal](18,6) NULL,
    [close_vs_sma_20_pct] [decimal](18,6) NULL,
    [close_vs_sma_50_pct] [decimal](18,6) NULL,
    [close_vs_sma_150_pct] [decimal](18,6) NULL,
    [close_vs_sma_200_pct] [decimal](18,6) NULL,
    [sma_20_slope_5d] [decimal](18,6) NULL,
    [sma_50_slope_10d] [decimal](18,6) NULL,
    [sma_150_slope_20d] [decimal](18,6) NULL,
    [sma_200_slope_20d] [decimal](18,6) NULL,
    [ma_alignment_bullish] [bit] NULL,
    [ma_alignment_bearish] [bit] NULL,
    [return_5d] [decimal](18,6) NULL,
    [return_10d] [decimal](18,6) NULL,
    [return_20d] [decimal](18,6) NULL,
    [return_60d] [decimal](18,6) NULL,
    [return_120d] [decimal](18,6) NULL,
    [return_250d] [decimal](18,6) NULL,
    [high_52w] [decimal](18,6) NULL,
    [low_52w] [decimal](18,6) NULL,
    [dist_to_52w_high_pct] [decimal](18,6) NULL,
    [dist_from_52w_low_pct] [decimal](18,6) NULL,
    [tr] [decimal](18,6) NULL,
    [atr_14] [decimal](18,6) NULL,
    [atr_pct_14] [decimal](18,6) NULL,
    [rolling_volatility_20d] [decimal](18,6) NULL,
    [avg_volume_20d] [decimal](18,2) NULL,
    [avg_volume_50d] [decimal](18,2) NULL,
    [rel_volume_1d] [decimal](18,6) NULL,
    [rel_volume_5d] [decimal](18,6) NULL,
    [rolling_range_10d_pct] [decimal](18,6) NULL,
    [rolling_range_20d_pct] [decimal](18,6) NULL,
    [rolling_range_50d_pct] [decimal](18,6) NULL,
    [spread_pct] [decimal](18,6) NULL,
    [median_spread_10d] [decimal](18,6) NULL,
    [median_spread_20d] [decimal](18,6) NULL,
    [created_at] [datetime2] NOT NULL DEFAULT (sysutcdatetime())
,
    CONSTRAINT [PK_price_feature_daily] PRIMARY KEY (symbol, trade_date)
);

CREATE INDEX [IX_price_feature_daily_trade_date] ON [TA].[price_feature_daily] (trade_date, symbol);