-- Table: [StockData].[DailyMarketSnapshot]

CREATE TABLE [StockData].[DailyMarketSnapshot] (
    [ASXCode] [varchar](20) NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [CaptureDateTime] [datetime2] NOT NULL,
    [MarketDataType] [tinyint] NULL,
    [LastPrice] [decimal](20,6) NULL,
    [ImpliedVolatility] [decimal](18,8) NULL,
    [HistoricalVolatility] [decimal](18,8) NULL,
    [IVRank252] [decimal](9,4) NULL,
    [IVPercentile252] [decimal](9,4) NULL,
    [IVHistoryCount] [smallint] NULL,
    [Low13Week] [decimal](20,6) NULL,
    [High13Week] [decimal](20,6) NULL,
    [Low26Week] [decimal](20,6) NULL,
    [High26Week] [decimal](20,6) NULL,
    [Low52Week] [decimal](20,6) NULL,
    [High52Week] [decimal](20,6) NULL,
    [AverageVolume90Day] [bigint] NULL,
    [ShortableShares] [bigint] NULL,
    [DividendPast12Months] [decimal](20,8) NULL,
    [DividendNext12Months] [decimal](20,8) NULL,
    [NextDividendDate] [date] NULL,
    [NextDividendAmount] [decimal](20,8) NULL,
    [DividendYieldPercent] [decimal](12,6) NULL,
    [CallVolume] [bigint] NULL,
    [PutVolume] [bigint] NULL,
    [CallOpenInterest] [bigint] NULL,
    [PutOpenInterest] [bigint] NULL,
    [AverageOptionVolume] [bigint] NULL,
    [PutCallVolumeRatio] [decimal](18,8) NULL,
    [PutCallOpenInterestRatio] [decimal](18,8) NULL,
    [TrailingPE] [decimal](20,8) NULL,
    [ForwardEPS] [decimal](20,8) NULL,
    [ForwardPE] [decimal](20,8) NULL,
    [MarketCap] [decimal](28,6) NULL,
    [Beta] [decimal](20,8) NULL,
    [PriceToBook] [decimal](20,8) NULL,
    [PayoutRatio] [decimal](20,8) NULL,
    [ReturnOnEquity] [decimal](20,8) NULL,
    [ReturnOnAssets] [decimal](20,8) NULL,
    [ReturnOnInvestment] [decimal](20,8) NULL,
    [DebtToEquity] [decimal](20,8) NULL,
    [RevenueGrowth] [decimal](20,8) NULL,
    [EPSGrowth] [decimal](20,8) NULL,
    [FreeCashFlow] [decimal](28,6) NULL,
    [FundamentalRatiosJson] [nvarchar](MAX) NULL,
    [DividendJson] [nvarchar](MAX) NULL,
    [CollectionStatus] [varchar](20) NOT NULL,
    [ErrorMessage] [nvarchar](1000) NULL,
    [CreateDate] [datetime2] NOT NULL DEFAULT (sysdatetime()),
    [ModifyDate] [datetime2] NOT NULL DEFAULT (sysdatetime())
,
    CONSTRAINT [PK_DailyMarketSnapshot] PRIMARY KEY (ASXCode, ObservationDate)
);

CREATE INDEX [IX_DailyMarketSnapshot_ObservationDate] ON [StockData].[DailyMarketSnapshot] (ImpliedVolatility, HistoricalVolatility, IVRank252, IVPercentile252, ObservationDate, CollectionStatus, ASXCode);