-- Table: [StockData].[StockAttribute]

CREATE TABLE [StockData].[StockAttribute] (
    [ASXCode] [varchar](10) NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [Close] [decimal](20,4) NOT NULL,
    [Open] [decimal](20,4) NOT NULL,
    [Low] [decimal](20,4) NOT NULL,
    [High] [decimal](20,4) NOT NULL,
    [Volume] [bigint] NOT NULL,
    [CreateDate] [smalldatetime] NOT NULL,
    [MovingAverage5d] [decimal](20,4) NULL,
    [MovingAverage10d] [decimal](20,4) NULL,
    [MovingAverage15d] [decimal](20,4) NULL,
    [MovingAverage20d] [decimal](20,4) NULL,
    [MovingAverage30d] [decimal](20,4) NULL,
    [MovingAverage60d] [decimal](20,4) NULL,
    [MovingAverage120d] [decimal](20,4) NULL,
    [MovingAverage135d] [decimal](20,4) NULL,
    [MovingAverage200d] [decimal](20,4) NULL,
    [MovingAverage5dVol] [decimal](20,4) NULL,
    [MovingAverage10dVol] [decimal](20,4) NULL,
    [MovingAverage15dVol] [decimal](20,4) NULL,
    [MovingAverage20dVol] [decimal](20,4) NULL,
    [MovingAverage30dVol] [decimal](20,4) NULL,
    [MovingAverage60dVol] [decimal](20,4) NULL,
    [MovingAverage120dVol] [decimal](20,4) NULL,
    [ExpMovingAverage7d] [decimal](20,4) NULL,
    [ExpMovingAverage15d] [decimal](20,4) NULL,
    [ExpMovingAverage30d] [decimal](20,4) NULL,
    [ExpMovingAverage50d] [decimal](20,4) NULL,
    [MaxClose5d] [decimal](20,4) NULL,
    [MaxClose10d] [decimal](20,4) NULL,
    [MaxClose15d] [decimal](20,4) NULL,
    [MaxClose20d] [decimal](20,4) NULL,
    [MinClose5d] [decimal](20,4) NULL,
    [MinClose10d] [decimal](20,4) NULL,
    [MinClose15d] [decimal](20,4) NULL,
    [MinClose20d] [decimal](20,4) NULL,
    [PriceSpread5d] [decimal](20,4) NULL,
    [PriceSpread10d] [decimal](20,4) NULL,
    [PriceSpread15d] [decimal](20,4) NULL,
    [PriceSpread20d] [decimal](20,4) NULL,
    [UpperShadowVsBodyRatio] [decimal](20,4) NULL,
    [BottomShadowVsBodyRatio] [decimal](20,4) NULL,
    [MACDMACD] [decimal](20,4) NULL,
    [MACDSignal] [decimal](20,4) NULL,
    [MACDHist] [decimal](20,4) NULL,
    [RSI] [decimal](20,4) NULL,
    [Support1] [decimal](20,4) NULL,
    [Support2] [decimal](20,4) NULL,
    [Support3] [decimal](20,4) NULL,
    [Resistence1] [decimal](20,4) NULL,
    [Resistence2] [decimal](20,4) NULL,
    [Resistence3] [decimal](20,4) NULL,
    [CLHL] [decimal](20,2) NULL,
    [BullEngulfing] [bit] NULL,
    [Doji] [bit] NULL,
    [DragonflyDoji] [bit] NULL,
    [EveningStar] [bit] NULL,
    [GravestoneDoji] [bit] NULL,
    [Hammer] [bit] NULL,
    [HangingMan] [bit] NULL,
    [HaramiPattern] [bit] NULL,
    [InvertedHammer] [bit] NULL,
    [LongLeggedDoji] [bit] NULL,
    [MorningStar] [bit] NULL,
    [PullBackReverse] [bit] NULL
);
