-- Table: [StockData].[MonthlyCurrent]

CREATE TABLE [StockData].[MonthlyCurrent] (
    [UniqueKey] [int] IDENTITY(1,1) NOT NULL,
    [ASXCode] [varchar](10) NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [Close] [decimal](20,4) NOT NULL,
    [Open] [decimal](20,4) NOT NULL,
    [Low] [decimal](20,4) NOT NULL,
    [High] [decimal](20,4) NOT NULL,
    [PrevClose] [decimal](20,4) NULL,
    [Volume] [bigint] NOT NULL,
    [IsTrendFlatOrUp] [bit] NULL,
    [CreateDate] [smalldatetime] NOT NULL,
    [DateSeq] [int] NULL,
    [Spread] [decimal](20,4) NULL,
    [GainLossPecentage] [decimal](20,4) NULL,
    [MovingAverage5d] [decimal](20,4) NULL,
    [MovingAverage10d] [decimal](20,4) NULL,
    [MovingAverage15d] [decimal](20,4) NULL,
    [MovingAverage20d] [decimal](20,4) NULL,
    [MovingAverage30d] [decimal](20,4) NULL,
    [MovingAverage60d] [decimal](20,4) NULL,
    [MovingAverage120d] [decimal](20,4) NULL,
    [MovingAverage135d] [decimal](20,4) NULL,
    [MovingAverage5dVol] [decimal](20,4) NULL,
    [MovingAverage10dVol] [decimal](20,4) NULL,
    [MovingAverage15dVol] [decimal](20,4) NULL,
    [MovingAverage20dVol] [decimal](20,4) NULL,
    [MovingAverage30dVol] [decimal](20,4) NULL,
    [MovingAverage60dVol] [decimal](20,4) NULL,
    [MovingAverage120dVol] [decimal](20,4) NULL,
    [DateSeqReverse] [int] NULL,
    [Prev3MovingAverage5d] [decimal](20,4) NULL,
    [Prev2MovingAverage5d] [decimal](20,4) NULL,
    [Prev1MovingAverage5d] [decimal](20,4) NULL,
    [RowNumber] [bigint] NULL
,
    CONSTRAINT [pk_stockdata_monthlycurrent_uniquekey] PRIMARY KEY (UniqueKey)
);
