-- Table: [Transform].[PriceHistoryFutureGainLoss]

CREATE TABLE [Transform].[PriceHistoryFutureGainLoss] (
    [ASXCode] [varchar](10) NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [Close] [decimal](20,4) NOT NULL,
    [Open] [decimal](20,4) NOT NULL,
    [Low] [decimal](20,4) NOT NULL,
    [High] [decimal](20,4) NOT NULL,
    [Volume] [bigint] NOT NULL,
    [Value] [decimal](20,4) NULL,
    [Trades] [int] NULL,
    [CreateDate] [smalldatetime] NOT NULL,
    [ModifyDate] [smalldatetime] NULL,
    [VWAP] [decimal](20,4) NULL,
    [AdditionalElements] [varchar](MAX) NULL,
    [IsSPX500] [bit] NULL,
    [IsDJIA30] [bit] NULL,
    [IsNASDAQ100] [bit] NULL,
    [PrevLow] [decimal](20,4) NULL,
    [PrevHigh] [decimal](20,4) NULL,
    [PrevClose] [decimal](20,4) NULL,
    [NextOpen] [decimal](20,4) NULL,
    [NextClose] [decimal](20,4) NULL,
    [Prev2Close] [decimal](20,4) NULL,
    [Prev3Close] [decimal](20,4) NULL,
    [Next2Close] [decimal](20,4) NULL,
    [Next5Close] [decimal](20,4) NULL,
    [Next10Close] [decimal](20,4) NULL,
    [TodayChange] [decimal](10,2) NULL,
    [TomorrowChange] [decimal](10,2) NULL,
    [TomorrowOpenChange] [decimal](10,2) NULL,
    [Next2DaysChange] [decimal](10,2) NULL,
    [Next5DaysChange] [decimal](10,2) NULL,
    [Next10DaysChange] [decimal](10,2) NULL,
    [YesterdayChange] [decimal](10,2) NULL,
    [Prev2DaysChange] [decimal](10,2) NULL,
    [Last2DaysChange] [decimal](10,2) NULL,
    [Last3DaysChange] [decimal](10,2) NULL,
    [HighestIn30D] [int] NULL,
    [HighestIn60D] [int] NULL,
    [SeqNo] [bigint] NULL
);
