-- Table: [Transform].[BrokerDailyFeature]

CREATE TABLE [Transform].[BrokerDailyFeature] (
    [ASXCode] [varchar](10) NOT NULL,
    [PriceASXCode] [varchar](10) NOT NULL,
    [TradeDate] [date] NOT NULL,
    [BrokerName] [varchar](200) NOT NULL,
    [BrokerCode] [varchar](50) NULL,
    [BuyValue] [decimal](20,4) NOT NULL,
    [SellValue] [decimal](20,4) NOT NULL,
    [NetValue] [decimal](20,4) NOT NULL,
    [TotalValue] [decimal](20,4) NULL,
    [DayOpen] [decimal](20,8) NOT NULL,
    [DayHigh] [decimal](20,8) NOT NULL,
    [DayLow] [decimal](20,8) NOT NULL,
    [DayClose] [decimal](20,8) NOT NULL,
    [DayVolume] [bigint] NOT NULL,
    [DayTurnover] [decimal](20,4) NOT NULL,
    [DayVWAP] [decimal](20,8) NULL,
    [NetBuyValue1D] [decimal](20,4) NOT NULL,
    [NetSellValue1D] [decimal](20,4) NOT NULL,
    [NetBuyRatio1D] [decimal](18,8) NOT NULL,
    [NetSellRatio1D] [decimal](18,8) NOT NULL,
    [BuyValueRatio1D] [decimal](18,8) NOT NULL,
    [SellValueRatio1D] [decimal](18,8) NOT NULL,
    [RollTurnover5D] [decimal](20,4) NULL,
    [RollTurnover7D] [decimal](20,4) NULL,
    [RollTurnover10D] [decimal](20,4) NULL,
    [RollTurnover20D] [decimal](20,4) NULL,
    [SumNetBuy5D] [decimal](20,4) NULL,
    [SumNetBuy7D] [decimal](20,4) NULL,
    [SumNetBuy10D] [decimal](20,4) NULL,
    [SumNetBuy20D] [decimal](20,4) NULL,
    [SumNetSell5D] [decimal](20,4) NULL,
    [SumNetSell7D] [decimal](20,4) NULL,
    [SumNetSell10D] [decimal](20,4) NULL,
    [SumNetSell20D] [decimal](20,4) NULL,
    [NetBuyRatio5D] [decimal](18,8) NULL,
    [NetBuyRatio7D] [decimal](18,8) NULL,
    [NetBuyRatio10D] [decimal](18,8) NULL,
    [NetBuyRatio20D] [decimal](18,8) NULL,
    [NetSellRatio5D] [decimal](18,8) NULL,
    [NetSellRatio7D] [decimal](18,8) NULL,
    [NetSellRatio10D] [decimal](18,8) NULL,
    [NetSellRatio20D] [decimal](18,8) NULL,
    [PositiveDays5D] [int] NULL,
    [PositiveDays7D] [int] NULL,
    [PositiveDays10D] [int] NULL,
    [NegativeDays5D] [int] NULL,
    [NegativeDays7D] [int] NULL,
    [NegativeDays10D] [int] NULL,
    [BuyStreakLength] [int] NULL,
    [SellStreakLength] [int] NULL,
    [NetToGrossRatio] [decimal](18,8) NULL,
    [BuyDominance] [decimal](18,8) NULL,
    [SellDominance] [decimal](18,8) NULL,
    [EstimatedNetShares1D] [decimal](28,8) NULL,
    [PositionSharesEst] [decimal](28,8) NULL,
    [CostValueEst] [decimal](28,8) NULL,
    [AvgCostEst] [decimal](20,8) NULL,
    [CloseVsAvgCost] [decimal](18,8) NULL,
    [VWAPVsAvgCost] [decimal](18,8) NULL,
    [ScoreVersion] [varchar](40) NOT NULL,
    [CreatedDate] [datetime2] NOT NULL DEFAULT (sysutcdatetime()),
    [ModifiedDate] [datetime2] NOT NULL DEFAULT (sysutcdatetime())
,
    CONSTRAINT [PK_Transform_BrokerDailyFeature] PRIMARY KEY (ASXCode, TradeDate, BrokerName)
);

CREATE INDEX [IX_Transform_BrokerDailyFeature_BrokerDate] ON [Transform].[BrokerDailyFeature] (BrokerName, TradeDate, ASXCode);
CREATE INDEX [IX_Transform_BrokerDailyFeature_TradeDate_ASXCode] ON [Transform].[BrokerDailyFeature] (TradeDate, ASXCode);