-- Table: [Transform].[BrokerHistoricalPerformance]

CREATE TABLE [Transform].[BrokerHistoricalPerformance] (
    [SnapshotDate] [date] NOT NULL,
    [BrokerName] [varchar](200) NOT NULL,
    [BrokerCode] [varchar](50) NULL,
    [EventType] [varchar](40) NOT NULL,
    [EventDirection] [varchar](10) NOT NULL,
    [EventCount] [int] NOT NULL,
    [StockCount] [int] NOT NULL,
    [AvgRet7D] [decimal](18,8) NULL,
    [AvgRet10D] [decimal](18,8) NULL,
    [AvgRet15D] [decimal](18,8) NULL,
    [AvgRet20D] [decimal](18,8) NULL,
    [AvgRet30D] [decimal](18,8) NULL,
    [AvgRet45D] [decimal](18,8) NULL,
    [AvgRet60D] [decimal](18,8) NULL,
    [MedianRet7D] [decimal](18,8) NULL,
    [MedianRet10D] [decimal](18,8) NULL,
    [MedianRet15D] [decimal](18,8) NULL,
    [MedianRet20D] [decimal](18,8) NULL,
    [MedianRet30D] [decimal](18,8) NULL,
    [MedianRet45D] [decimal](18,8) NULL,
    [MedianRet60D] [decimal](18,8) NULL,
    [StdRet7D] [decimal](18,8) NULL,
    [StdRet10D] [decimal](18,8) NULL,
    [StdRet15D] [decimal](18,8) NULL,
    [StdRet20D] [decimal](18,8) NULL,
    [StdRet30D] [decimal](18,8) NULL,
    [StdRet45D] [decimal](18,8) NULL,
    [StdRet60D] [decimal](18,8) NULL,
    [WinRate7D] [decimal](18,8) NULL,
    [WinRate10D] [decimal](18,8) NULL,
    [WinRate15D] [decimal](18,8) NULL,
    [WinRate20D] [decimal](18,8) NULL,
    [WinRate30D] [decimal](18,8) NULL,
    [WinRate45D] [decimal](18,8) NULL,
    [WinRate60D] [decimal](18,8) NULL,
    [LargeWinnerRate20D] [decimal](18,8) NULL,
    [LargeWinnerRate30D] [decimal](18,8) NULL,
    [LargeWinnerRate60D] [decimal](18,8) NULL,
    [LargeLoserRate20D] [decimal](18,8) NULL,
    [LargeLoserRate30D] [decimal](18,8) NULL,
    [LargeLoserRate60D] [decimal](18,8) NULL,
    [AvgMaxUp30D] [decimal](18,8) NULL,
    [AvgMaxDD30D] [decimal](18,8) NULL,
    [AvgMaxUp60D] [decimal](18,8) NULL,
    [AvgMaxDD60D] [decimal](18,8) NULL,
    [ReliabilityScore] [decimal](18,8) NOT NULL,
    [HistoricalEdgeScore] [decimal](18,8) NOT NULL,
    [BrokerArchetype] [varchar](50) NOT NULL,
    [ScoreVersion] [varchar](40) NOT NULL,
    [CreatedDate] [datetime2] NOT NULL DEFAULT (sysutcdatetime())
,
    CONSTRAINT [PK_Transform_BrokerHistoricalPerformance] PRIMARY KEY (SnapshotDate, BrokerName, EventType)
);

CREATE INDEX [IX_Transform_BrokerHistoricalPerformance_Lookup] ON [Transform].[BrokerHistoricalPerformance] (BrokerName, SnapshotDate, EventDirection, HistoricalEdgeScore);