-- Table: [Transform].[MostTradedSmallCap]

CREATE TABLE [Transform].[MostTradedSmallCap] (
    [ReportType] [varchar](20) NOT NULL,
    [RefreshTime] [varchar](8) NULL,
    [ASXCode] [varchar](10) NOT NULL,
    [ObservationDate] [date] NULL,
    [Close] [decimal](20,4) NULL,
    [SurplusVolume] [int] NULL,
    [MatchVolume] [nvarchar](4000) NULL,
    [MatchValue] [nvarchar](4000) NULL,
    [Bid] [int] NULL,
    [Ask] [int] NULL,
    [ChangePerc] [decimal](10,2) NULL,
    [OpenChangePerc] [decimal](10,2) NULL,
    [BarStrength] [int] NULL,
    [AnnDescr] [varchar](200) NULL,
    [FriendlyNameList] [nvarchar](MAX) NULL,
    [MC] [decimal](8,2) NULL,
    [CashPosition] [decimal](8,2) NULL,
    [T/O Rate] [decimal](20,2) NULL,
    [T/O in K] [int] NULL,
    [ObservationDayTopBuyBroker] [varchar](1000) NULL,
    [ObservationDayTopSellBroker] [varchar](1000) NULL,
    [RecentTopBuyBroker] [varchar](1000) NULL,
    [RecentTopSellBroker] [varchar](1000) NULL,
    [InstTradeValue] [nvarchar](4000) NULL,
    [InstTradeValue%] [nvarchar](4000) NULL,
    [AvgTradeValuePerc] [decimal](10,2) NULL,
    [InstBuy%] [nvarchar](4000) NULL,
    [RetailBuy%] [nvarchar](4000) NULL,
    [InstBuyVWAP] [decimal](38,6) NULL,
    [RetailBuyVWAP] [decimal](38,6) NULL,
    [AboveLongMA] [int] NOT NULL,
    [TrendUpLongMA] [int] NOT NULL,
    [IndustrySubGroup] [varchar](200) NULL,
    [Notes] [int] NULL
);
