-- Table: [Transform].[PriceHistorySecondarySMART]

CREATE TABLE [Transform].[PriceHistorySecondarySMART] (
    [ASXCode] [varchar](10) NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [Prev1ObservationDate] [date] NULL,
    [Prev2ObservationDate] [date] NULL,
    [Prev3ObservationDate] [date] NULL,
    [Close] [decimal](20,4) NOT NULL,
    [Open] [decimal](20,4) NOT NULL,
    [Low] [decimal](20,4) NOT NULL,
    [High] [decimal](20,4) NOT NULL,
    [Volume] [bigint] NOT NULL,
    [Value] [decimal](20,4) NULL,
    [Trades] [int] NULL,
    [Exchange] [varchar](20) NOT NULL,
    [CreateDate] [smalldatetime] NOT NULL,
    [ModifyDate] [smalldatetime] NULL,
    [VWAP] [decimal](20,4) NULL,
    [AdditionalElements] [varchar](MAX) NULL,
    [SMA5] [float] NULL,
    [SMA10] [float] NULL,
    [SMA20] [float] NULL,
    [SMA50] [float] NULL,
    [SMA100] [float] NULL,
    [SMA200] [float] NULL,
    [BBand_Upper] [float] NULL,
    [BBand_Middle] [float] NULL,
    [BBand_Lower] [float] NULL,
    [ATR] [float] NULL,
    [NATR] [float] NULL,
    [TRANGE] [float] NULL,
    [RSI6] [float] NULL,
    [RSI14] [float] NULL,
    [Stoch_SlowK] [float] NULL,
    [Stoch_SlowD] [float] NULL,
    [MACD_MACD] [float] NULL,
    [MACD_Signal] [float] NULL,
    [MACD_Hist] [float] NULL
);
