-- Table: [Transform].[PriceSummaryMatchVolume]

CREATE TABLE [Transform].[PriceSummaryMatchVolume] (
    [PriceSummaryID] [int] NULL,
    [ASXCode] [varchar](10) NOT NULL,
    [Bid] [int] NULL,
    [Offer] [int] NULL,
    [Open] [decimal](20,4) NOT NULL,
    [High] [decimal](20,4) NOT NULL,
    [Low] [decimal](20,4) NOT NULL,
    [Close] [decimal](20,4) NOT NULL,
    [Volume] [bigint] NOT NULL,
    [Value] [decimal](20,4) NULL,
    [Trades] [int] NULL,
    [VWAP] [decimal](31,15) NULL,
    [DateFrom] [smalldatetime] NOT NULL,
    [DateTo] [int] NULL,
    [LastVerifiedDate] [smalldatetime] NOT NULL,
    [bids] [int] NULL,
    [bidsTotalVolume] [int] NULL,
    [offers] [int] NULL,
    [offersTotalVolume] [int] NULL,
    [IndicativePrice] [int] NULL,
    [SurplusVolume] [int] NULL,
    [MatchVolume] [int] NULL,
    [PrevClose] [decimal](20,4) NULL,
    [SysLastSaleDate] [int] NULL,
    [SysCreateDate] [int] NULL,
    [Prev1PriceSummaryID] [int] NULL,
    [Prev1Bid] [int] NULL,
    [Prev1Offer] [int] NULL,
    [Prev1Volume] [int] NULL,
    [Prev1Value] [int] NULL,
    [VolumeDelta] [int] NULL,
    [ValueDelta] [int] NULL,
    [TimeIntervalInSec] [int] NULL,
    [BuySellInd] [int] NULL,
    [Prev1Close] [int] NULL,
    [LatestForTheDay] [int] NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [RowNumber] [bigint] NULL
);

CREATE INDEX [idx_transformpricesummarymatchvolume_obdateasxcode] ON [Transform].[PriceSummaryMatchVolume] (ObservationDate, ASXCode);