-- Table: [Transform].[PriceHistory24Month]

CREATE TABLE [Transform].[PriceHistory24Month] (
    [ReverseRowNumber] [int] NULL,
    [ASXCode] [varchar](10) NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [Close] [decimal](20,4) NOT NULL,
    [Open] [decimal](20,4) NOT NULL,
    [Low] [decimal](20,4) NOT NULL,
    [High] [decimal](20,4) NOT NULL,
    [Volume] [bigint] NOT NULL,
    [Value] [decimal](20,4) NULL,
    [Trades] [int] NULL,
    [CreateDate] [smalldatetime] NOT NULL,
    [ModifyDate] [smalldatetime] NULL,
    [PrevLow] [decimal](20,4) NULL,
    [PrevHigh] [decimal](20,4) NULL,
    [PrevClose] [decimal](20,4) NULL,
    [NextOpen] [decimal](20,4) NULL,
    [NextLow] [decimal](20,4) NULL,
    [NextHigh] [decimal](20,4) NULL,
    [NextClose] [decimal](20,4) NULL,
    [Prev2Close] [decimal](20,4) NULL,
    [Prev3Close] [decimal](20,4) NULL,
    [Prev11Close] [decimal](20,4) NULL,
    [Next2Close] [decimal](20,4) NULL,
    [Next5Close] [decimal](20,4) NULL,
    [Next10Close] [decimal](20,4) NULL,
    [TodayChange] [decimal](10,2) NULL,
    [TomorrowChange] [decimal](10,2) NULL,
    [TomorrowOpenChange] [decimal](10,2) NULL,
    [Next2DaysChange] [decimal](10,2) NULL,
    [Next5DaysChange] [decimal](10,2) NULL,
    [Next10DaysChange] [decimal](10,2) NULL,
    [YesterdayChange] [decimal](10,2) NULL,
    [Prev2DaysChange] [decimal](10,2) NULL,
    [Prev10DaysChange] [decimal](10,2) NULL,
    [Last2DaysChange] [decimal](10,2) NULL,
    [Last3DaysChange] [decimal](10,2) NULL,
    [SMA10] [decimal](18,6) NULL,
    [SMA50] [decimal](18,6) NULL,
    [PriceChangePct] [decimal](18,4) NULL,
    [TodayVolume] [bigint] NOT NULL,
    [TodaySMA10] [decimal](18,6) NULL,
    [T1_SMA10] [decimal](18,6) NULL,
    [T1_SMA50] [decimal](18,6) NULL,
    [T1_Volume] [bigint] NULL,
    [T1_PriceChangePct] [decimal](18,4) NULL,
    [T2_SMA10] [decimal](18,6) NULL,
    [T2_SMA50] [decimal](18,6) NULL,
    [T2_Volume] [bigint] NULL,
    [T2_PriceChangePct] [decimal](18,4) NULL
);

CREATE INDEX [idx_transformpricehistory24month_asxobdata] ON [Transform].[PriceHistory24Month] (TodayChange, Next2DaysChange, Next5DaysChange, Next10DaysChange, ASXCode, ObservationDate);