-- Table: [Transform].[PriceSummaryLatest]

CREATE TABLE [Transform].[PriceSummaryLatest] (
    [PriceSummaryID] [int] IDENTITY(1,1) NOT NULL,
    [ASXCode] [varchar](10) NOT NULL,
    [Bid] [decimal](20,4) NULL,
    [Offer] [decimal](20,4) NULL,
    [Open] [decimal](20,4) NULL,
    [High] [decimal](20,4) NULL,
    [Low] [decimal](20,4) NULL,
    [Close] [decimal](20,4) NULL,
    [Volume] [bigint] NULL,
    [Value] [decimal](20,4) NULL,
    [Trades] [int] NULL,
    [VWAP] [decimal](20,4) NULL,
    [DateFrom] [datetime] NOT NULL,
    [DateTo] [datetime] NULL,
    [LastVerifiedDate] [smalldatetime] NULL,
    [bids] [decimal](20,4) NULL,
    [bidsTotalVolume] [bigint] NULL,
    [offers] [decimal](20,4) NULL,
    [offersTotalVolume] [bigint] NULL,
    [IndicativePrice] [decimal](20,4) NULL,
    [SurplusVolume] [bigint] NULL,
    [MatchVolume] [int] NULL,
    [PrevClose] [decimal](20,4) NULL,
    [SysLastSaleDate] [datetime] NULL,
    [SysCreateDate] [datetime] NULL,
    [Prev1PriceSummaryID] [int] NULL,
    [Prev1Bid] [decimal](20,4) NULL,
    [Prev1Offer] [decimal](20,4) NULL,
    [Prev1Volume] [bigint] NULL,
    [Prev1Value] [decimal](20,4) NULL,
    [VolumeDelta] [int] NULL,
    [ValueDelta] [decimal](20,4) NULL,
    [TimeIntervalInSec] [int] NULL,
    [BuySellInd] [char](1) NULL,
    [Prev1Close] [decimal](20,4) NULL,
    [LatestForTheDay] [bit] NULL,
    [ObservationDate] [date] NULL,
    [PriceChangeVsPrevClose] [decimal](10,2) NULL,
    [PriceChangeVsOpen] [decimal](10,2) NULL,
    [Spread] [decimal](21,4) NULL
);

CREATE INDEX [idx_transformpricesummarylatest_obdateasxcode] ON [Transform].[PriceSummaryLatest] (ObservationDate, ASXCode);