-- Table: [Transform].[ScanResultHistory]

CREATE TABLE [Transform].[ScanResultHistory] (
    [ScanResultHistoryID] [int] IDENTITY(1,1) NOT NULL,
    [ASXCode] [varchar](10) NOT NULL,
    [AlertTypeName] [varchar](MAX) NULL,
    [AlertCreateDate] [smalldatetime] NOT NULL,
    [Grade] [numeric](3,1) NULL,
    [RetraceScore] [numeric](3,1) NULL,
    [IndustrySubGroup] [varchar](200) NULL,
    [MC] [decimal](8,2) NULL,
    [CashPosition] [decimal](8,2) NULL,
    [T/O in K] [int] NULL,
    [MedianValue Wk] [int] NULL,
    [MedianValue Day] [int] NULL,
    [MedianPriceChg] [decimal](10,2) NULL,
    [PrevDayChangePerc] [decimal](10,2) NULL,
    [TodayChangePerc] [decimal](10,2) NULL,
    [T/O Rate] [decimal](10,2) NULL,
    [NextDayOpenProfit] [decimal](10,2) NULL,
    [NextDayCloseProfit] [decimal](10,2) NULL,
    [ObservationDayTopBuyBroker] [varchar](MAX) NULL,
    [ObservationDayTopSellBroker] [varchar](MAX) NULL,
    [RecentTopBuyBroker] [varchar](MAX) NULL,
    [RecentTopSellBroker] [varchar](MAX) NULL,
    [VsMA5] [decimal](10,2) NULL,
    [VsMA10] [decimal](10,2) NULL,
    [AnnDescr] [varchar](200) NULL,
    [NoBuy] [int] NULL,
    [NoSig] [int] NULL,
    [WkMon+] [int] NULL,
    [MT Retail %] [decimal](10,2) NULL,
    [ST Retail %] [decimal](10,2) NULL,
    [BarStrength] [int] NULL,
    [AlertTypeScore] [int] NULL
,
    CONSTRAINT [pk_transform_scanresulthistory_scanresulthistoryid] PRIMARY KEY (ScanResultHistoryID)
);
