-- Table: [Analysis].[GEX_Features_DEV]

CREATE TABLE [Analysis].[GEX_Features_DEV] (
    [ObservationDate] [date] NULL,
    [ASXCode] [varchar](10) NULL,
    [BTC] [decimal](20,4) NULL,
    [VIX] [decimal](20,4) NULL,
    [Gold] [decimal](20,4) NULL,
    [NASDAQ] [decimal](20,4) NULL,
    [Stock_DarkPoolBuySellRatio] [decimal](10,2) NULL,
    [Stock_DarkPoolIndex] [decimal](10,1) NULL,
    [SVix_DarkPoolBuyRatio] [decimal](10,2) NULL,
    [SVix_DarkPoolIndex] [decimal](10,1) NULL,
    [BuyCall_GEXDeltaPerc] [decimal](10,2) NULL,
    [BuyPut_GEXDeltaPerc] [decimal](10,2) NULL,
    [Close] [decimal](20,4) NULL,
    [TodayChange] [decimal](10,2) NULL,
    [TomorrowChange] [decimal](10,2) NULL,
    [Next2DaysChange] [decimal](10,2) NULL,
    [Next5DaysChange] [decimal](10,2) NULL,
    [Next10DaysChange] [decimal](10,2) NULL,
    [Next20DaysChange] [decimal](10,2) NULL,
    [Prev2DaysChange] [decimal](10,2) NULL,
    [Prev10DaysChange] [decimal](10,2) NULL,
    [RSI] [numeric](38,29) NULL,
    [GEX] [float] NULL,
    [Prev1GEX] [float] NULL,
    [GEXChange] [decimal](10,2) NULL,
    [GEX_Positive] [int] NOT NULL,
    [GEX_Negative] [int] NOT NULL,
    [GEX_DayChange] [float] NULL,
    [GEX_ZScore] [float] NULL,
    [GEX_ZScore_60day] [float] NULL,
    [GEX_Percentile] [float] NULL,
    [GEX_ZScore_VeryLow] [int] NOT NULL,
    [GEX_ZScore_Low] [int] NOT NULL,
    [GEX_ZScore_Moderate_Low] [int] NOT NULL,
    [GEX_ZScore_High] [int] NOT NULL,
    [GEX_ZScore_VeryHigh] [int] NOT NULL,
    [GEX_Percentile_VeryLow] [int] NOT NULL,
    [GEX_Percentile_Low] [int] NOT NULL,
    [GEX_Percentile_High] [int] NOT NULL,
    [GEX_Percentile_VeryHigh] [int] NOT NULL,
    [GEX_SMA5] [float] NULL,
    [GEX_SMA10] [float] NULL,
    [GEX_SMA20] [float] NULL,
    [GEX_Above_SMA10] [int] NOT NULL,
    [GEX_Above_SMA20] [int] NOT NULL,
    [GEX_Trending_Up] [int] NOT NULL,
    [GEX_PctChange] [float] NULL,
    [GEX_Rising] [int] NOT NULL,
    [GEX_Falling] [int] NOT NULL,
    [GEX_Volatility] [float] NULL,
    [GEX_HighVolatility] [int] NOT NULL,
    [GEX_StableRegime] [int] NOT NULL,
    [GEX_Turned_Positive] [int] NOT NULL,
    [GEX_Turned_Negative] [int] NOT NULL,
    [GEX_Escaped_VeryLow_Zscore] [int] NOT NULL,
    [GEX_Escaped_VeryHigh_Zscore] [int] NOT NULL,
    [SwingIndicator] [varchar](10) NULL,
    [PotentialSwingIndicator] [varchar](20) NULL,
    [Is_Swing_Up] [int] NOT NULL,
    [Is_Swing_Down] [int] NOT NULL,
    [Is_Potential_Swing_Up] [int] NOT NULL,
    [Is_Potential_Swing_Down] [int] NOT NULL,
    [GEXChange_Positive] [int] NOT NULL,
    [GEXChange_Negative] [int] NOT NULL,
    [GEX_BigDrop] [int] NOT NULL,
    [GEX_BigRise] [int] NOT NULL,
    [Price_SMA5] [decimal](38,6) NULL,
    [Price_SMA10] [decimal](38,6) NULL,
    [Price_SMA20] [decimal](38,6) NULL,
    [Price_SMA50] [decimal](38,6) NULL,
    [Price_SMA100] [decimal](38,6) NULL,
    [Price_SMA200] [decimal](38,6) NULL,
    [Price_Above_SMA5] [int] NOT NULL,
    [Price_Above_SMA10] [int] NOT NULL,
    [Price_Above_SMA20] [int] NOT NULL,
    [Price_Above_SMA50] [int] NOT NULL,
    [Price_Above_SMA100] [int] NOT NULL,
    [Price_Above_SMA200] [int] NOT NULL,
    [Price_Below_SMA5] [int] NOT NULL,
    [Price_Below_SMA10] [int] NOT NULL,
    [Price_Below_SMA20] [int] NOT NULL,
    [Price_Below_SMA50] [int] NOT NULL,
    [Price_Below_SMA100] [int] NOT NULL,
    [Price_Below_SMA200] [int] NOT NULL,
    [Price_Near_SMA5] [int] NOT NULL,
    [Price_Near_SMA10] [int] NOT NULL,
    [Price_Near_SMA20] [int] NOT NULL,
    [Price_Near_SMA50] [int] NOT NULL,
    [Price_Near_SMA100] [int] NOT NULL,
    [Price_Near_SMA200] [int] NOT NULL,
    [Price_VeryClose_SMA20] [int] NOT NULL,
    [Price_VeryClose_SMA50] [int] NOT NULL,
    [Price_VeryClose_SMA200] [int] NOT NULL,
    [Dist_To_SMA5] [decimal](38,6) NULL,
    [Dist_To_SMA10] [decimal](38,6) NULL,
    [Dist_To_SMA20] [decimal](38,6) NULL,
    [Dist_To_SMA50] [decimal](38,6) NULL,
    [Dist_To_SMA100] [decimal](38,6) NULL,
    [Dist_To_SMA200] [decimal](38,6) NULL,
    [Dist_To_SMA5_Pct] [decimal](38,6) NULL,
    [Dist_To_SMA10_Pct] [decimal](38,6) NULL,
    [Dist_To_SMA20_Pct] [decimal](38,6) NULL,
    [Dist_To_SMA50_Pct] [decimal](38,6) NULL,
    [Dist_To_SMA100_Pct] [decimal](38,6) NULL,
    [Dist_To_SMA200_Pct] [decimal](38,6) NULL,
    [MA_Bullish_Alignment_Short] [int] NOT NULL,
    [MA_Bullish_Alignment_Long] [int] NOT NULL,
    [MA_Bearish_Alignment_Short] [int] NOT NULL,
    [MA_Bearish_Alignment_Long] [int] NOT NULL,
    [SMA20_Above_SMA50] [int] NOT NULL,
    [SMA50_Above_SMA200] [int] NOT NULL,
    [Golden_Cross_Formation] [int] NOT NULL,
    [Death_Cross_Formation] [int] NOT NULL,
    [BB10_Upper] [float] NULL,
    [BB10_Middle] [decimal](38,6) NULL,
    [BB10_Lower] [float] NULL,
    [BB10_PercentB] [float] NULL,
    [BB10_Bandwidth] [float] NULL,
    [BB20_Upper] [float] NULL,
    [BB20_Middle] [decimal](38,6) NULL,
    [BB20_Lower] [float] NULL,
    [BB20_Upper_1Std] [float] NULL,
    [BB20_Lower_1Std] [float] NULL,
    [BB20_PercentB] [float] NULL,
    [BB20_Bandwidth] [float] NULL,
    [BB50_Upper] [float] NULL,
    [BB50_Middle] [decimal](38,6) NULL,
    [BB50_Lower] [float] NULL,
    [BB50_PercentB] [float] NULL,
    [BB50_Bandwidth] [float] NULL,
    [BB10_Breakout_Upper] [int] NOT NULL,
    [BB10_Breakout_Lower] [int] NOT NULL,
    [BB10_In_Upper_Half] [int] NOT NULL,
    [BB10_In_Lower_Half] [int] NOT NULL,
    [BB20_Breakout_Upper] [int] NOT NULL,
    [BB20_Breakout_Lower] [int] NOT NULL,
    [BB20_In_Upper_Half] [int] NOT NULL,
    [BB20_In_Lower_Half] [int] NOT NULL,
    [BB50_Breakout_Upper] [int] NOT NULL,
    [BB50_Breakout_Lower] [int] NOT NULL,
    [Price_Near_BB20_Upper] [int] NOT NULL,
    [Price_Near_BB20_Lower] [int] NOT NULL,
    [Price_Near_BB50_Upper] [int] NOT NULL,
    [Price_Near_BB50_Lower] [int] NOT NULL,
    [Dist_To_BB10_Upper] [float] NULL,
    [Dist_To_BB10_Lower] [float] NULL,
    [Dist_To_BB10_Upper_Pct] [float] NULL,
    [Dist_To_BB10_Lower_Pct] [float] NULL,
    [Dist_To_BB20_Upper] [float] NULL,
    [Dist_To_BB20_Lower] [float] NULL,
    [Dist_To_BB20_Upper_Pct] [float] NULL,
    [Dist_To_BB20_Lower_Pct] [float] NULL,
    [Dist_To_BB50_Upper] [float] NULL,
    [Dist_To_BB50_Lower] [float] NULL,
    [Dist_To_BB50_Upper_Pct] [float] NULL,
    [Dist_To_BB50_Lower_Pct] [float] NULL,
    [BB20_Squeeze_Tight] [int] NOT NULL,
    [BB20_Squeeze_Moderate] [int] NOT NULL,
    [BB20_Wide_Range] [int] NOT NULL,
    [BB50_Squeeze_Tight] [int] NOT NULL,
    [BB50_Wide_Range] [int] NOT NULL,
    [BB20_Walking_Upper_Band] [int] NOT NULL,
    [BB20_Walking_Lower_Band] [int] NOT NULL,
    [Price_ROC_1day] [decimal](38,13) NULL,
    [Price_ROC_2day] [decimal](38,13) NULL,
    [Price_ROC_5day] [decimal](38,13) NULL,
    [Price_ROC_10day] [decimal](38,13) NULL,
    [Price_ROC_20day] [decimal](38,13) NULL,
    [Strong_Upward_Momentum_5d] [int] NOT NULL,
    [Strong_Downward_Momentum_5d] [int] NOT NULL,
    [Strong_Upward_Momentum_20d] [int] NOT NULL,
    [Strong_Downward_Momentum_20d] [int] NOT NULL,
    [MACD_Line] [decimal](38,6) NULL,
    [MACD_Positive] [int] NOT NULL,
    [MACD_Negative] [int] NOT NULL,
    [Positive_GEX_AND_Uptrend] [int] NOT NULL,
    [Negative_GEX_AND_Downtrend] [int] NOT NULL,
    [Positive_GEX_BUT_Oversold] [int] NOT NULL,
    [Negative_GEX_BUT_Overbought] [int] NOT NULL,
    [GEX_Rising_With_Price] [int] NOT NULL,
    [GEX_Falling_With_Price] [int] NOT NULL,
    [GEX_Price_Divergence_Bullish] [int] NOT NULL,
    [GEX_Price_Divergence_Bearish] [int] NOT NULL,
    [Pot_Swing_Up_AND_Neg_GEXChange] [int] NOT NULL,
    [Low_GEX_Z_AND_Pot_Swing_Up] [int] NOT NULL,
    [Golden_Setup] [int] NOT NULL,
    [VIX_Very_High] [int] NOT NULL,
    [Negative_GEX_AND_High_VIX] [int] NOT NULL,
    [Setup_Trend_Dip] [int] NOT NULL,
    [Setup_Dual_Squeeze] [int] NOT NULL,
    [Setup_Volatility_Crush] [int] NOT NULL,
    [Oversold_Dip_In_Uptrend] [int] NOT NULL,
    [Overbought_Pop_In_Downtrend] [int] NOT NULL,
    [Triple_Oversold_Signal] [int] NOT NULL,
    [Strong_Bullish_Confirmation] [int] NOT NULL,
    [Coiling_For_Breakout] [int] NOT NULL
);
