-- Table: [Analysis].[GEX_Features]

CREATE TABLE [Analysis].[GEX_Features] (
    [ObservationDate] [date] NULL,
    [ASXCode] [varchar](10) NULL,
    [BTC] [decimal](20,4) NULL,
    [VIX] [decimal](20,4) NULL,
    [Gold] [decimal](20,4) NULL,
    [NASDAQ] [decimal](20,4) NULL,
    [Stock_DarkPoolBuySellRatio] [decimal](10,2) NULL,
    [Stock_DarkPoolIndex] [decimal](10,1) NULL,
    [SVix_DarkPoolBuyRatio] [decimal](10,2) NULL,
    [SVix_DarkPoolIndex] [decimal](10,1) NULL,
    [BuyCall_GEXDeltaPerc] [decimal](10,2) NULL,
    [BuyPut_GEXDeltaPerc] [decimal](10,2) NULL,
    [Close] [decimal](20,4) NULL,
    [TodayChange] [decimal](10,2) NULL,
    [TomorrowChange] [decimal](10,2) NULL,
    [Next2DaysChange] [decimal](10,2) NULL,
    [Next5DaysChange] [decimal](10,2) NULL,
    [Next10DaysChange] [decimal](10,2) NULL,
    [Next20DaysChange] [decimal](10,2) NULL,
    [Prev2DaysChange] [decimal](10,2) NULL,
    [Prev10DaysChange] [decimal](10,2) NULL,
    [RSI] [numeric](38,29) NULL,
    [GEX] [float] NULL,
    [Prev1GEX] [float] NULL,
    [GEXChange] [decimal](10,2) NULL,
    [GEX_Positive] [int] NOT NULL,
    [GEX_Negative] [int] NOT NULL,
    [GEX_DayChange] [float] NULL,
    [GEX_ZScore] [float] NULL,
    [GEX_ZScore_60day] [float] NULL,
    [GEX_Percentile] [float] NULL,
    [GEX_ZScore_VeryLow] [int] NOT NULL,
    [GEX_ZScore_Low] [int] NOT NULL,
    [GEX_ZScore_Moderate_Low] [int] NOT NULL,
    [GEX_ZScore_High] [int] NOT NULL,
    [GEX_ZScore_VeryHigh] [int] NOT NULL,
    [GEX_Percentile_VeryLow] [int] NOT NULL,
    [GEX_Percentile_Low] [int] NOT NULL,
    [GEX_Percentile_High] [int] NOT NULL,
    [GEX_Percentile_VeryHigh] [int] NOT NULL,
    [GEX_SMA5] [float] NULL,
    [GEX_SMA10] [float] NULL,
    [GEX_SMA20] [float] NULL,
    [GEX_Above_SMA10] [int] NOT NULL,
    [GEX_Above_SMA20] [int] NOT NULL,
    [GEX_Trending_Up] [int] NOT NULL,
    [GEX_PctChange] [float] NULL,
    [GEX_Rising] [int] NOT NULL,
    [GEX_Falling] [int] NOT NULL,
    [GEX_Volatility] [float] NULL,
    [GEX_HighVolatility] [int] NOT NULL,
    [GEX_StableRegime] [int] NOT NULL,
    [GEX_Turned_Positive] [int] NOT NULL,
    [GEX_Turned_Negative] [int] NOT NULL,
    [GEX_Escaped_VeryLow_Zscore] [int] NOT NULL,
    [GEX_Escaped_VeryHigh_Zscore] [int] NOT NULL,
    [SwingIndicator] [varchar](10) NULL,
    [PotentialSwingIndicator] [varchar](20) NULL,
    [Is_Swing_Up] [int] NOT NULL,
    [Is_Swing_Down] [int] NOT NULL,
    [Is_Potential_Swing_Up] [int] NOT NULL,
    [Is_Potential_Swing_Down] [int] NOT NULL,
    [GEXChange_Positive] [int] NOT NULL,
    [GEXChange_Negative] [int] NOT NULL,
    [GEX_BigDrop] [int] NOT NULL,
    [GEX_BigRise] [int] NOT NULL,
    [Price_SMA20] [decimal](38,6) NULL,
    [Price_SMA50] [decimal](38,6) NULL,
    [Price_Above_SMA20] [int] NOT NULL,
    [Price_Above_SMA50] [int] NOT NULL,
    [SMA20_Above_SMA50] [int] NOT NULL,
    [BB_Upper] [float] NULL,
    [BB_Lower] [float] NULL,
    [BB_Breakout_Upper] [int] NOT NULL,
    [BB_Breakout_Lower] [int] NOT NULL,
    [BB_PercentB] [float] NULL,
    [BB_Bandwidth] [float] NULL,
    [MACD_Line] [decimal](38,6) NULL,
    [MACD_Positive] [int] NOT NULL,
    [Pot_Swing_Up_AND_Neg_GEXChange] [int] NOT NULL,
    [Low_GEX_Z_AND_Pot_Swing_Up] [int] NOT NULL,
    [Golden_Setup] [int] NOT NULL,
    [VIX_Very_High] [int] NOT NULL,
    [Negative_GEX_AND_High_VIX] [int] NOT NULL,
    [Setup_Trend_Dip] [int] NOT NULL,
    [Setup_Dual_Squeeze] [int] NOT NULL,
    [Setup_Volatility_Crush] [int] NOT NULL
);
