-- View: [StockData].[v_BrokerReport]


create view StockData.v_BrokerReport
as
SELECT [BrokerReportID]
      ,[ASXCode]
      ,[ObservationDate]
      ,[BrokerCode]
      ,[Symbol]
      ,[BuyValue]
      ,[SellValue]
      ,[NetValue]
      ,[TotalValue]
      ,[BuyVolume]
      ,[SellVolume]
      ,[NetVolume]
      ,[TotalVolume]
      ,[NoBuys]
      ,[NoSells]
      ,[Trades]
      ,[BuyPrice]
      ,[SellPrice]
      ,[PercRank]
      ,[CreateDate]
FROM [StockData].[BrokerReport]
union all
SELECT [BrokerReportID]
      ,[ASXCode]
      ,[ObservationDate]
      ,[BrokerCode]
      ,[Symbol]
      ,[BuyValue]
      ,[SellValue]
      ,[NetValue]
      ,[TotalValue]
      ,[BuyVolume]
      ,[SellVolume]
      ,[NetVolume]
      ,[TotalVolume]
      ,[NoBuys]
      ,[NoSells]
      ,[Trades]
      ,[BuyPrice]
      ,[SellPrice]
      ,[PercRank]
      ,[CreateDate]
FROM ArchiveDB.[StockData].[BrokerReport]
