-- View: [StockData].[v_PriceSummary]








CREATE view [StockData].[v_PriceSummary]
as
SELECT 
	   checksum(ASXCode, ObservationDate) as [PriceSummaryID]
      ,[ASXCode]
      ,null as [Bid]
      ,null as [Offer]
      ,[Open]
      ,[High]
      ,[Low]
      ,[Close]
      ,[Volume]
      ,[Value]
      ,[Trades]
      ,case when Trades > 0 then Value/Trades else null end as [VWAP]
      ,CreateDate as [DateFrom]
      ,null as [DateTo]
      ,CreateDate as [LastVerifiedDate]
      ,null as [bids]
      ,null as [bidsTotalVolume]
      ,null as [offers]
      ,null as [offersTotalVolume]
      ,null as [IndicativePrice]
      ,null as [SurplusVolume]
	  ,null as [MatchVolume]
      ,PrevClose as [PrevClose]
      ,null as [SysLastSaleDate]
      ,null as [SysCreateDate]
      ,null as [Prev1PriceSummaryID]
      ,null as [Prev1Bid]
      ,null as [Prev1Offer]
      ,null as [Prev1Volume]
      ,null as [Prev1Value]
      ,null as [VolumeDelta]
      ,null as [ValueDelta]
      ,null as [TimeIntervalInSec]
      ,null as [BuySellInd]
      ,null as [Prev1Close]
      ,1 as [LatestForTheDay]
      ,[ObservationDate]
FROM Transform.PriceHistory
where Volume > 0
and [Value] > 0
--union all
--SELECT top 100 [PriceSummaryID]
--      ,[ASXCode]
--      ,[Bid]
--      ,[Offer]
--      ,[Open]
--      ,[High]
--      ,[Low]
--      ,[Close]
--      ,[Volume]
--      ,[Value]
--      ,[Trades]
--      ,[VWAP]
--      ,[DateFrom]
--      ,[DateTo]
--      ,[LastVerifiedDate]
--      ,[bids]
--      ,[bidsTotalVolume]
--      ,[offers]
--      ,[offersTotalVolume]
--      ,[IndicativePrice]
--      ,[SurplusVolume]
--	  ,[MatchVolume]
--      ,[PrevClose]
--      ,[SysLastSaleDate]
--      ,[SysCreateDate]
--      ,[Prev1PriceSummaryID]
--      ,[Prev1Bid]
--      ,[Prev1Offer]
--      ,[Prev1Volume]
--      ,[Prev1Value]
--      ,[VolumeDelta]
--      ,[ValueDelta]
--      ,[TimeIntervalInSec]
--      ,[BuySellInd]
--      ,[Prev1Close]
--      ,[LatestForTheDay]
--      ,[ObservationDate]
--FROM [StockData].[PriceSummary] with(nolock)
--union all
--SELECT [PriceSummaryID]
--      ,[ASXCode]
--      ,[Bid]
--      ,[Offer]
--      ,[Open]
--      ,[High]
--      ,[Low]
--      ,[Close]
--      ,[Volume]
--      ,[Value]
--      ,[Trades]
--      ,[VWAP]
--      ,[DateFrom]
--      ,[DateTo]
--      ,[LastVerifiedDate]
--      ,[bids]
--      ,[bidsTotalVolume]
--      ,[offers]
--      ,[offersTotalVolume]
--      ,[IndicativePrice]
--      ,[SurplusVolume]
--	  ,[MatchVolume]
--      ,[PrevClose]
--      ,[SysLastSaleDate]
--      ,[SysCreateDate]
--      ,[Prev1PriceSummaryID]
--      ,[Prev1Bid]
--      ,[Prev1Offer]
--      ,[Prev1Volume]
--      ,[Prev1Value]
--      ,[VolumeDelta]
--      ,[ValueDelta]
--      ,[TimeIntervalInSec]
--      ,[BuySellInd]
--      ,[Prev1Close]
--      ,[LatestForTheDay]
--      ,[ObservationDate]
--FROM [StockData].[PriceSummaryToday] with(nolock)


