-- View: [StockData].[v_StockStatsHistoryPlusCurrent]





CREATE view [StockData].[v_StockStatsHistoryPlusCurrent]
as
SELECT [ASXCode]
      ,[ObservationDate]
      ,[Close]
      ,[Open]
      ,[Low]
      ,[High]
      ,[PrevClose]
      ,[Volume]
	  ,case when MovingAverage5d > 0 then ([Close]-MovingAverage5d)*100.0/MovingAverage5d else null end as BIAS5d
	  ,case when MovingAverage10d > 0 then ([Close]-MovingAverage10d)*100.0/MovingAverage10d else null end as BIAS10d
	  ,case when MovingAverage30d > 0 then ([Close]-MovingAverage30d)*100.0/MovingAverage30d else null end as BIAS30d
      ,[IsTrendFlatOrUp]
      ,[CreateDate]
      ,[DateSeq]
      ,[Spread]
      ,[GainLossPecentage]
      ,[MovingAverage5d]
      ,[MovingAverage10d]
      ,[MovingAverage15d]
      ,[MovingAverage20d]
      ,[MovingAverage30d]
      ,[MovingAverage60d]
      ,[MovingAverage120d]
      ,[MovingAverage135d]
      ,[MovingAverage5dVol]
      ,[MovingAverage10dVol]
      ,[MovingAverage15dVol]
      ,[MovingAverage20dVol]
      ,[MovingAverage30dVol]
      ,[MovingAverage60dVol]
      ,[MovingAverage120dVol]
      ,[ExpMovingAverage7d]
      ,[ExpMovingAverage15d]
      ,[ExpMovingAverage25d]
      ,[ExpMovingAverage235d]
      ,[MaxClose5d]
      ,[MaxClose10d]
      ,[MaxClose15d]
      ,[MaxClose20d]
      ,[MinClose5d]
      ,[MinClose10d]
      ,[MinClose15d]
      ,[MinClose20d]
      ,[PriceSpread5d]
      ,[PriceSpread10d]
      ,[PriceSpread15d]
      ,[PriceSpread20d]
      ,[UpperShadowVsBodyRatio]
      ,[BottomShadowVsBodyRatio]
      ,[MACDMACD]
      ,[MACDSignal]
      ,[MACDHist]
      ,[RSI]
      ,[Previous30dHigh]
      ,[Previous30dLow]
      ,[Next60dHigh]
      ,[Next60dLow]
      ,[Next30dHigh]
      ,[Next30dLow]
      ,[Support1]
      ,[Support2]
      ,[Support3]
      ,[Resistence1]
      ,[Resistence2]
      ,[Resistence3]
      ,[EMA7After10d]
      ,[EMA710dChange]
      ,[EMA7After5d]
      ,[EMA75dChange]
      ,[EMA7After20d]
      ,[EMA720dChange]
      ,[PriceBand]
      ,[EMA7dOverEMA15d]
      ,[SMA30dOverSMA60d]
      ,[PriceOverSMA60d]
      ,[PriceOverSMA30d]
      ,[PriceOverEMA7d]
      ,[PriceOverEMA15d]
      ,[VolumeOver3xVol120d]
      ,[VolumeOver5xVol120d]
      ,[PriceOverMaxClose20d]
      ,[PriceUnderMinClose20d]
      ,[PriceEMAMove5d]
      ,[PriceEMAMove10d]
      ,[PriceEMAMove20d]
      ,[PriceDirection]
      ,[CLHL]
      ,[MACDHistTurnUp]
      ,[MACDCrossUp]
      ,[Next5dHigh]
      ,[Next10dHigh]
      ,[Next5dLow]
      ,[Next10dLow]
      ,[Previous90dHigh]
      ,[Previous60dHigh]
      ,[Previous60dLow]
      ,[BullEngulfing]
      ,[MovingAverage200d]
	  ,null as TrendMovingAverage60d
	  ,null as TrendMovingAverage200d
      ,[DateSeqReverse]
FROM [Alert].[StockStatsHistoryPlusCurrent]
union all
select [ASXCode]
      ,[ObservationDate]
      ,[Close]
      ,[Open]
      ,[Low]
      ,[High]
      ,[PrevClose]
      ,[Volume]
	  ,case when MovingAverage5d > 0 then ([Close]-MovingAverage5d)*100.0/MovingAverage5d else null end as BIAS5d
	  ,case when MovingAverage10d > 0 then ([Close]-MovingAverage10d)*100.0/MovingAverage10d else null end as BIAS10d
	  ,case when MovingAverage30d > 0 then ([Close]-MovingAverage30d)*100.0/MovingAverage30d else null end as BIAS30d
      ,[IsTrendFlatOrUp]
      ,[CreateDate]
      ,[DateSeq]
      ,[Spread]
      ,[GainLossPecentage]
      ,[MovingAverage5d]
      ,[MovingAverage10d]
      ,[MovingAverage15d]
      ,[MovingAverage20d]
      ,[MovingAverage30d]
      ,[MovingAverage60d]
      ,[MovingAverage120d]
      ,[MovingAverage135d]
      ,[MovingAverage5dVol]
      ,[MovingAverage10dVol]
      ,[MovingAverage15dVol]
      ,[MovingAverage20dVol]
      ,[MovingAverage30dVol]
      ,[MovingAverage60dVol]
      ,[MovingAverage120dVol]
      ,[ExpMovingAverage7d]
      ,[ExpMovingAverage15d]
      ,[ExpMovingAverage25d]
      ,[ExpMovingAverage235d]
      ,[MaxClose5d]
      ,[MaxClose10d]
      ,[MaxClose15d]
      ,[MaxClose20d]
      ,[MinClose5d]
      ,[MinClose10d]
      ,[MinClose15d]
      ,[MinClose20d]
      ,[PriceSpread5d]
      ,[PriceSpread10d]
      ,[PriceSpread15d]
      ,[PriceSpread20d]
      ,[UpperShadowVsBodyRatio]
      ,[BottomShadowVsBodyRatio]
      ,[MACDMACD]
      ,[MACDSignal]
      ,[MACDHist]
      ,[RSI]
      ,[Previous30dHigh]
      ,[Previous30dLow]
      ,[Next60dHigh]
      ,[Next60dLow]
      ,[Next30dHigh]
      ,[Next30dLow]
      ,[Support1]
      ,[Support2]
      ,[Support3]
      ,[Resistence1]
      ,[Resistence2]
      ,[Resistence3]
      ,[EMA7After10d]
      ,[EMA710dChange]
      ,[EMA7After5d]
      ,[EMA75dChange]
      ,[EMA7After20d]
      ,[EMA720dChange]
      ,[PriceBand]
      ,[EMA7dOverEMA15d]
      ,[SMA30dOverSMA60d]
      ,[PriceOverSMA60d]
      ,[PriceOverSMA30d]
      ,[PriceOverEMA7d]
      ,[PriceOverEMA15d]
      ,[VolumeOver3xVol120d]
      ,[VolumeOver5xVol120d]
      ,[PriceOverMaxClose20d]
      ,[PriceUnderMinClose20d]
      ,[PriceEMAMove5d]
      ,[PriceEMAMove10d]
      ,[PriceEMAMove20d]
      ,[PriceDirection]
      ,[CLHL]
      ,[MACDHistTurnUp]
      ,[MACDCrossUp]
      ,[Next5dHigh]
      ,[Next10dHigh]
      ,[Next5dLow]
      ,[Next10dLow]
      ,[Previous90dHigh]
      ,[Previous60dHigh]
      ,[Previous60dLow]
      ,[BullEngulfing]
      ,[MovingAverage200d]
	  ,TrendMovingAverage60d
	  ,TrendMovingAverage200d
      ,[DateSeqReverse]
FROM [StockData].[StockStatsHistoryPlusCurrent] as a
where not exists
(
	select 1
	from [Alert].[StockStatsHistoryPlusCurrent]
	where ASXCode = a.ASXCode
)

