-- View: [StockData].[v_DailyMarketSnapshot_Latest]


create view [StockData].[v_DailyMarketSnapshot_Latest]
as
select *
from
(
	SELECT [ASXCode]
		  ,[ObservationDate]
		  ,[CaptureDateTime]
		  ,[MarketDataType]
		  ,[LastPrice]
		  ,[ImpliedVolatility]
		  ,[HistoricalVolatility]
		  ,[IVRank252]
		  ,[IVPercentile252]
		  ,[IVHistoryCount]
		  ,[Low13Week]
		  ,[High13Week]
		  ,[Low26Week]
		  ,[High26Week]
		  ,[Low52Week]
		  ,[High52Week]
		  ,[AverageVolume90Day]
		  ,[ShortableShares]
		  ,[DividendPast12Months]
		  ,[DividendNext12Months]
		  ,[NextDividendDate]
		  ,[NextDividendAmount]
		  ,[DividendYieldPercent]
		  ,[CallVolume]
		  ,[PutVolume]
		  ,[CallOpenInterest]
		  ,[PutOpenInterest]
		  ,[AverageOptionVolume]
		  ,[PutCallVolumeRatio]
		  ,[PutCallOpenInterestRatio]
		  ,[TrailingPE]
		  ,[ForwardEPS]
		  ,[ForwardPE]
		  ,[MarketCap]
		  ,[Beta]
		  ,[PriceToBook]
		  ,[PayoutRatio]
		  ,[ReturnOnEquity]
		  ,[ReturnOnAssets]
		  ,[ReturnOnInvestment]
		  ,[DebtToEquity]
		  ,[RevenueGrowth]
		  ,[EPSGrowth]
		  ,[FreeCashFlow]
		  ,[FundamentalRatiosJson]
		  ,[DividendJson]
		  ,[CollectionStatus]
		  ,[ErrorMessage]
		  ,[CreateDate]
		  ,[ModifyDate]
		  ,row_number() over (partition by ASXCode order by ObservationDate desc) as RowNumber
	FROM [StockData].[DailyMarketSnapshot]
) as x
where x.RowNumber = 1

