-- View: [StockData].[v_PriceSummary]





CREATE view [StockData].[v_PriceSummary]
as
SELECT [PriceSummaryID]
      ,[ASXCode]
      ,[Bid]
      ,[Offer]
      ,[Open]
      ,[High]
      ,[Low]
      ,[Close]
      ,[Volume]
      ,[Value]
      ,[Trades]
      ,[VWAP]
      ,[DateFrom]
      ,[DateTo]
      ,[LastVerifiedDate]
      ,[bids]
      ,[bidsTotalVolume]
      ,[offers]
      ,[offersTotalVolume]
      ,[IndicativePrice]
      ,[SurplusVolume]
	  ,[MatchVolume]
      ,[PrevClose]
      ,[SysLastSaleDate]
      ,[SysCreateDate]
      ,[Prev1PriceSummaryID]
      ,[Prev1Bid]
      ,[Prev1Offer]
      ,[Prev1Volume]
      ,[Prev1Value]
      ,[VolumeDelta]
      ,[ValueDelta]
      ,[TimeIntervalInSec]
      ,[BuySellInd]
      ,[Prev1Close]
      ,[LatestForTheDay]
      ,[ObservationDate]
FROM [StockData].[PriceSummary]
union all
SELECT [PriceSummaryID]
      ,[ASXCode]
      ,[Bid]
      ,[Offer]
      ,[Open]
      ,[High]
      ,[Low]
      ,[Close]
      ,[Volume]
      ,[Value]
      ,[Trades]
      ,[VWAP]
      ,[DateFrom]
      ,[DateTo]
      ,[LastVerifiedDate]
      ,[bids]
      ,[bidsTotalVolume]
      ,[offers]
      ,[offersTotalVolume]
      ,[IndicativePrice]
      ,[SurplusVolume]
	  ,[MatchVolume]
      ,[PrevClose]
      ,[SysLastSaleDate]
      ,[SysCreateDate]
      ,[Prev1PriceSummaryID]
      ,[Prev1Bid]
      ,[Prev1Offer]
      ,[Prev1Volume]
      ,[Prev1Value]
      ,[VolumeDelta]
      ,[ValueDelta]
      ,[TimeIntervalInSec]
      ,[BuySellInd]
      ,[Prev1Close]
      ,[LatestForTheDay]
      ,[ObservationDate]
FROM [StockData].[PriceSummaryToday]
