-- Table: [Alert].[StockStatsHistoryPlusCurrent]

CREATE TABLE [Alert].[StockStatsHistoryPlusCurrent] (
    [ASXCode] [varchar](10) NOT NULL,
    [ObservationDate] [date] NOT NULL,
    [Close] [decimal](20,4) NOT NULL,
    [Open] [decimal](20,4) NOT NULL,
    [Low] [decimal](20,4) NOT NULL,
    [High] [decimal](20,4) NOT NULL,
    [PrevClose] [decimal](20,4) NULL,
    [Volume] [bigint] NOT NULL,
    [IsTrendFlatOrUp] [bit] NULL,
    [CreateDate] [smalldatetime] NOT NULL,
    [DateSeq] [int] NULL,
    [Spread] [decimal](20,4) NULL,
    [GainLossPecentage] [decimal](20,4) NULL,
    [MovingAverage3d] [decimal](20,4) NULL,
    [MovingAverage5d] [decimal](20,4) NULL,
    [MovingAverage10d] [decimal](20,4) NULL,
    [MovingAverage15d] [decimal](20,4) NULL,
    [MovingAverage20d] [decimal](20,4) NULL,
    [MovingAverage30d] [decimal](20,4) NULL,
    [MovingAverage60d] [decimal](20,4) NULL,
    [MovingAverage120d] [decimal](20,4) NULL,
    [MovingAverage135d] [decimal](20,4) NULL,
    [MovingAverage5dVol] [decimal](20,4) NULL,
    [MovingAverage10dVol] [decimal](20,4) NULL,
    [MovingAverage15dVol] [decimal](20,4) NULL,
    [MovingAverage20dVol] [decimal](20,4) NULL,
    [MovingAverage30dVol] [decimal](20,4) NULL,
    [MovingAverage60dVol] [decimal](20,4) NULL,
    [MovingAverage120dVol] [decimal](20,4) NULL,
    [ExpMovingAverage7d] [decimal](20,4) NULL,
    [ExpMovingAverage15d] [decimal](20,4) NULL,
    [ExpMovingAverage25d] [decimal](20,4) NULL,
    [ExpMovingAverage235d] [decimal](20,4) NULL,
    [MaxClose5d] [decimal](20,4) NULL,
    [MaxClose10d] [decimal](20,4) NULL,
    [MaxClose15d] [decimal](20,4) NULL,
    [MaxClose20d] [decimal](20,4) NULL,
    [MinClose5d] [decimal](20,4) NULL,
    [MinClose10d] [decimal](20,4) NULL,
    [MinClose15d] [decimal](20,4) NULL,
    [MinClose20d] [decimal](20,4) NULL,
    [PriceSpread5d] [decimal](20,4) NULL,
    [PriceSpread10d] [decimal](20,4) NULL,
    [PriceSpread15d] [decimal](20,4) NULL,
    [PriceSpread20d] [decimal](20,4) NULL,
    [UpperShadowVsBodyRatio] [decimal](20,4) NULL,
    [BottomShadowVsBodyRatio] [decimal](20,4) NULL,
    [MACDMACD] [decimal](20,4) NULL,
    [MACDSignal] [decimal](20,4) NULL,
    [MACDHist] [decimal](20,4) NULL,
    [RSI] [decimal](20,4) NULL,
    [Previous30dHigh] [date] NULL,
    [Previous30dLow] [date] NULL,
    [Next60dHigh] [date] NULL,
    [Next60dLow] [date] NULL,
    [Next30dHigh] [date] NULL,
    [Next30dLow] [date] NULL,
    [Support1] [decimal](20,4) NULL,
    [Support2] [decimal](20,4) NULL,
    [Support3] [decimal](20,4) NULL,
    [Resistence1] [decimal](20,4) NULL,
    [Resistence2] [decimal](20,4) NULL,
    [Resistence3] [decimal](20,4) NULL,
    [EMA7After10d] [decimal](20,4) NULL,
    [EMA710dChange] [decimal](20,4) NULL,
    [EMA7After5d] [decimal](20,4) NULL,
    [EMA75dChange] [decimal](20,4) NULL,
    [EMA7After20d] [decimal](20,4) NULL,
    [EMA720dChange] [decimal](20,4) NULL,
    [PriceBand] [int] NULL,
    [EMA7dOverEMA15d] [bit] NULL,
    [SMA30dOverSMA60d] [bit] NULL,
    [PriceOverSMA60d] [bit] NULL,
    [PriceOverSMA30d] [bit] NULL,
    [PriceOverEMA7d] [bit] NULL,
    [PriceOverEMA15d] [bit] NULL,
    [VolumeOver3xVol120d] [bit] NULL,
    [VolumeOver5xVol120d] [bit] NULL,
    [PriceOverMaxClose20d] [bit] NULL,
    [PriceUnderMinClose20d] [bit] NULL,
    [PriceEMAMove5d] [varchar](100) NULL,
    [PriceEMAMove10d] [varchar](100) NULL,
    [PriceEMAMove20d] [varchar](100) NULL,
    [PriceDirection] [varchar](50) NULL,
    [CLHL] [decimal](20,2) NULL,
    [MACDHistTurnUp] [bit] NULL,
    [MACDCrossUp] [bit] NULL,
    [Next5dHigh] [decimal](20,5) NULL,
    [Next10dHigh] [decimal](20,5) NULL,
    [Next5dLow] [decimal](20,5) NULL,
    [Next10dLow] [decimal](20,5) NULL,
    [Previous90dHigh] [decimal](20,5) NULL,
    [Previous60dHigh] [decimal](20,5) NULL,
    [Previous60dLow] [decimal](20,5) NULL,
    [BullEngulfing] [bit] NULL,
    [MovingAverage200d] [decimal](20,4) NULL,
    [DateSeqReverse] [int] NULL,
    [UniqueKey] [int] IDENTITY(1,1) NOT NULL,
    [PredictNextDayMovingAverage5d] [decimal](20,4) NULL
,
    CONSTRAINT [pk_alert_stockstatshistorypluscurrent_uniquekey] PRIMARY KEY (UniqueKey)
);
